package com.cps;

import com.cps.Formulario.*;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

public class CPSTeste {

    @Test
    public void deve_criar_um_teste_com_100_questoes(){

        Formulario escalasDePersonalidade = new Formulario("Escalas de Personalidade COMREY");//criado a classe formulario e o construtor do formulario

        Escala escala1 = new Escala("Nunca / Certamente não", 1);
        Escala escala2 = new Escala("Muito raramente / Muito provavelmente que não", 2);
        Escala escala3 = new Escala("Raramente / Provavelmente não", 3);
        Escala escala4 = new Escala("Ocasionalmente / Possivelmente", 4);
        Escala escala5 = new Escala("Frequemtente / Provavelmente sim", 5);
        Escala escala6 = new Escala("Muito frequentemente / Provavelmente sim", 6);
        Escala escala7 = new Escala("Sempre / Certamente sim", 7);

        List<Escala> escalas = new ArrayList<Escala>();

        Questao a1 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a2 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a3 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a4 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a5 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a6 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a7 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a8 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a9 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a10 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a11 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a12 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a13 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a14 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a15 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a16 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a17 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a18 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a19 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a20 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a21 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a22 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a23 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a24 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a25 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a26 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a27 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a28 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a29 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a30 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a31 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a32 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a33 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a34 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a35 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a36 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a37 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a38 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a39 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a40 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a41 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a42 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a43 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a44 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a45 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a46 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a47 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a48 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a49 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a50 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a51 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a52 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a53 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a54 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a55 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a56 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a57 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a58 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a59 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a60 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a61 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a62 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a63 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a64 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a65 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a66 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a67 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a68 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a69 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a70 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a71 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a72 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a73 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a74 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a75 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a76 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a77 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a78 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a79 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a80 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a81 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a82 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a83 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a84 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a85 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a86 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a87 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a88 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a89 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a90 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a91 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a92 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a93 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a94 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a95 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a96 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a97 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a98 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a99 = new Questao("A maioria das pessoas é honesta? ", escalas);
        Questao a100 = new Questao("A maioria das pessoas é honesta? ", escalas);

        escalasDePersonalidade.adicionar(a1);
        escalasDePersonalidade.adicionar(a2);
        escalasDePersonalidade.adicionar(a3);
        escalasDePersonalidade.adicionar(a4);
        escalasDePersonalidade.adicionar(a5);
        escalasDePersonalidade.adicionar(a6);
        escalasDePersonalidade.adicionar(a7);
        escalasDePersonalidade.adicionar(a8);
        escalasDePersonalidade.adicionar(a9);
        escalasDePersonalidade.adicionar(a10);
        escalasDePersonalidade.adicionar(a11);
        escalasDePersonalidade.adicionar(a12);
        escalasDePersonalidade.adicionar(a13);
        escalasDePersonalidade.adicionar(a14);
        escalasDePersonalidade.adicionar(a15);
        escalasDePersonalidade.adicionar(a16);
        escalasDePersonalidade.adicionar(a17);
        escalasDePersonalidade.adicionar(a18);
        escalasDePersonalidade.adicionar(a19);
        escalasDePersonalidade.adicionar(a20);
        escalasDePersonalidade.adicionar(a21);
        escalasDePersonalidade.adicionar(a22);
        escalasDePersonalidade.adicionar(a23);
        escalasDePersonalidade.adicionar(a24);
        escalasDePersonalidade.adicionar(a25);
        escalasDePersonalidade.adicionar(a26);
        escalasDePersonalidade.adicionar(a27);
        escalasDePersonalidade.adicionar(a28);
        escalasDePersonalidade.adicionar(a29);
        escalasDePersonalidade.adicionar(a30);
        escalasDePersonalidade.adicionar(a31);
        escalasDePersonalidade.adicionar(a32);
        escalasDePersonalidade.adicionar(a33);
        escalasDePersonalidade.adicionar(a34);
        escalasDePersonalidade.adicionar(a35);
        escalasDePersonalidade.adicionar(a36);
        escalasDePersonalidade.adicionar(a37);
        escalasDePersonalidade.adicionar(a38);
        escalasDePersonalidade.adicionar(a39);
        escalasDePersonalidade.adicionar(a40);
        escalasDePersonalidade.adicionar(a41);
        escalasDePersonalidade.adicionar(a42);
        escalasDePersonalidade.adicionar(a43);
        escalasDePersonalidade.adicionar(a44);
        escalasDePersonalidade.adicionar(a45);
        escalasDePersonalidade.adicionar(a46);
        escalasDePersonalidade.adicionar(a47);
        escalasDePersonalidade.adicionar(a48);
        escalasDePersonalidade.adicionar(a49);
        escalasDePersonalidade.adicionar(a50);
        escalasDePersonalidade.adicionar(a51);
        escalasDePersonalidade.adicionar(a52);
        escalasDePersonalidade.adicionar(a53);
        escalasDePersonalidade.adicionar(a54);
        escalasDePersonalidade.adicionar(a55);
        escalasDePersonalidade.adicionar(a56);
        escalasDePersonalidade.adicionar(a57);
        escalasDePersonalidade.adicionar(a58);
        escalasDePersonalidade.adicionar(a59);
        escalasDePersonalidade.adicionar(a60);
        escalasDePersonalidade.adicionar(a61);
        escalasDePersonalidade.adicionar(a62);
        escalasDePersonalidade.adicionar(a63);
        escalasDePersonalidade.adicionar(a64);
        escalasDePersonalidade.adicionar(a65);
        escalasDePersonalidade.adicionar(a66);
        escalasDePersonalidade.adicionar(a67);
        escalasDePersonalidade.adicionar(a68);
        escalasDePersonalidade.adicionar(a69);
        escalasDePersonalidade.adicionar(a70);
        escalasDePersonalidade.adicionar(a71);
        escalasDePersonalidade.adicionar(a72);
        escalasDePersonalidade.adicionar(a73);
        escalasDePersonalidade.adicionar(a74);
        escalasDePersonalidade.adicionar(a75);
        escalasDePersonalidade.adicionar(a76);
        escalasDePersonalidade.adicionar(a77);
        escalasDePersonalidade.adicionar(a78);
        escalasDePersonalidade.adicionar(a79);
        escalasDePersonalidade.adicionar(a80);
        escalasDePersonalidade.adicionar(a81);
        escalasDePersonalidade.adicionar(a82);
        escalasDePersonalidade.adicionar(a83);
        escalasDePersonalidade.adicionar(a84);
        escalasDePersonalidade.adicionar(a85);
        escalasDePersonalidade.adicionar(a86);
        escalasDePersonalidade.adicionar(a87);
        escalasDePersonalidade.adicionar(a88);
        escalasDePersonalidade.adicionar(a89);
        escalasDePersonalidade.adicionar(a90);
        escalasDePersonalidade.adicionar(a91);
        escalasDePersonalidade.adicionar(a92);
        escalasDePersonalidade.adicionar(a93);
        escalasDePersonalidade.adicionar(a94);
        escalasDePersonalidade.adicionar(a95);
        escalasDePersonalidade.adicionar(a96);
        escalasDePersonalidade.adicionar(a97);
        escalasDePersonalidade.adicionar(a98);
        escalasDePersonalidade.adicionar(a99);
        escalasDePersonalidade.adicionar(a100);

        System.out.println(escalasDePersonalidade.getNome());
        System.out.println(a1.getEnunciado());
        System.out.println("1-"+escala1.gerDescricao()+"\n"
                +"2-"+escala2.gerDescricao()+"\n"
                +"3-"+escala3.gerDescricao()+"\n"
                +"4-"+escala4.gerDescricao()+"\n"
                +"5-"+escala5.gerDescricao()+"\n"
                +"6-"+escala6.gerDescricao()+"\n"
                +"7-"+escala7.gerDescricao()+"\n");

        Gabarito gabaritoEscalaDePersonalidadeComrey = new Gabarito("Gabarito Escala de Personalidade Comrey");
        Resposta respostaA1 = new Resposta(a1, escala2);
        Resposta respostaA2 = new Resposta(a2, escala1);
        Resposta respostaA3 = new Resposta(a3, escala5);
        Resposta respostaA4 = new Resposta(a4, escala3);
        Resposta respostaA5 = new Resposta(a5, escala7);
        Resposta respostaA6 = new Resposta(a6, escala1);
        Resposta respostaA7 = new Resposta(a7, escala1);
        Resposta respostaA8 = new Resposta(a8, escala6);
        Resposta respostaA9 = new Resposta(a9, escala4);
        Resposta respostaA10 = new Resposta(a10, escala1);
        Resposta respostaA11 = new Resposta(a11, escala7);
        Resposta respostaA12 = new Resposta(a12, escala7);
        Resposta respostaA13 = new Resposta(a13, escala3);
        Resposta respostaA14 = new Resposta(a14, escala3);
        Resposta respostaA15 = new Resposta(a15, escala3);
        Resposta respostaA16 = new Resposta(a16, escala2);
        Resposta respostaA17 = new Resposta(a17, escala1);
        Resposta respostaA18 = new Resposta(a18, escala2);
        Resposta respostaA19 = new Resposta(a19, escala3);
        Resposta respostaA20 = new Resposta(a20, escala4);
        Resposta respostaA21 = new Resposta(a21, escala4);
        Resposta respostaA22 = new Resposta(a22, escala7);
        Resposta respostaA23 = new Resposta(a23, escala6);
        Resposta respostaA24 = new Resposta(a24, escala1);
        Resposta respostaA25 = new Resposta(a25, escala7);
        Resposta respostaA26 = new Resposta(a26, escala4);
        Resposta respostaA27 = new Resposta(a27, escala7);
        Resposta respostaA28 = new Resposta(a28, escala1);
        Resposta respostaA29 = new Resposta(a29, escala7);
        Resposta respostaA30 = new Resposta(a30, escala4);
        Resposta respostaA31 = new Resposta(a31, escala5);
        Resposta respostaA32 = new Resposta(a32, escala4);
        Resposta respostaA33 = new Resposta(a33, escala2);
        Resposta respostaA34 = new Resposta(a34, escala5);
        Resposta respostaA35 = new Resposta(a34, escala4);
        Resposta respostaA36 = new Resposta(a36, escala2);
        Resposta respostaA37 = new Resposta(a37, escala1);
        Resposta respostaA38 = new Resposta(a38, escala5);
        Resposta respostaA39 = new Resposta(a39, escala4);
        Resposta respostaA40 = new Resposta(a40, escala1);
        Resposta respostaA41 = new Resposta(a41, escala5);
        Resposta respostaA42 = new Resposta(a42, escala3);
        Resposta respostaA43 = new Resposta(a43, escala7);
        Resposta respostaA44 = new Resposta(a44, escala4);
        Resposta respostaA45 = new Resposta(a45, escala1);
        Resposta respostaA46 = new Resposta(a46, escala4);
        Resposta respostaA47 = new Resposta(a47, escala7);
        Resposta respostaA48 = new Resposta(a48, escala4);
        Resposta respostaA49 = new Resposta(a49, escala3);
        Resposta respostaA50 = new Resposta(a50, escala5);
        Resposta respostaA51 = new Resposta(a51, escala1);
        Resposta respostaA52 = new Resposta(a52, escala4);
        Resposta respostaA53 = new Resposta(a53, escala6);
        Resposta respostaA54 = new Resposta(a54, escala7);
        Resposta respostaA55 = new Resposta(a55, escala7);
        Resposta respostaA56 = new Resposta(a56, escala7);
        Resposta respostaA57 = new Resposta(a57, escala1);
        Resposta respostaA58 = new Resposta(a58, escala3);
        Resposta respostaA59 = new Resposta(a59, escala7);
        Resposta respostaA60 = new Resposta(a60, escala5);
        Resposta respostaA61 = new Resposta(a61, escala5);
        Resposta respostaA62 = new Resposta(a62, escala6);
        Resposta respostaA63 = new Resposta(a63, escala1);
        Resposta respostaA64 = new Resposta(a64, escala1);
        Resposta respostaA65 = new Resposta(a65, escala7);
        Resposta respostaA66 = new Resposta(a66, escala2);
        Resposta respostaA67 = new Resposta(a67, escala5);
        Resposta respostaA68 = new Resposta(a68, escala7);
        Resposta respostaA69 = new Resposta(a69, escala1);
        Resposta respostaA70 = new Resposta(a70, escala7);
        Resposta respostaA71 = new Resposta(a71, escala7);
        Resposta respostaA72 = new Resposta(a72, escala1);
        Resposta respostaA73 = new Resposta(a73, escala7);
        Resposta respostaA74 = new Resposta(a74, escala7);
        Resposta respostaA75 = new Resposta(a75, escala1);
        Resposta respostaA76 = new Resposta(a76, escala5);
        Resposta respostaA77 = new Resposta(a77, escala1);
        Resposta respostaA78 = new Resposta(a78, escala7);
        Resposta respostaA79 = new Resposta(a79, escala3);
        Resposta respostaA80 = new Resposta(a80, escala1);
        Resposta respostaA81 = new Resposta(a81, escala4);
        Resposta respostaA82 = new Resposta(a82, escala4);
        Resposta respostaA83 = new Resposta(a83, escala1);
        Resposta respostaA84 = new Resposta(a84, escala2);
        Resposta respostaA85 = new Resposta(a85, escala7);
        Resposta respostaA86 = new Resposta(a86, escala4);
        Resposta respostaA87 = new Resposta(a87, escala7);
        Resposta respostaA88 = new Resposta(a88, escala1);
        Resposta respostaA89 = new Resposta(a89, escala1);
        Resposta respostaA90 = new Resposta(a90, escala7);
        Resposta respostaA91 = new Resposta(a91, escala3);
        Resposta respostaA92 = new Resposta(a92, escala4);
        Resposta respostaA93 = new Resposta(a93, escala5);
        Resposta respostaA94 = new Resposta(a94, escala7);
        Resposta respostaA95 = new Resposta(a95, escala1);
        Resposta respostaA96 = new Resposta(a96, escala1);
        Resposta respostaA97 = new Resposta(a97, escala1);
        Resposta respostaA98 = new Resposta(a98, escala7);
        Resposta respostaA99 = new Resposta(a99, escala7);
        Resposta respostaA100 = new Resposta(a100, escala1);

        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA1);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA2);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA3);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA4);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA5);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA6);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA7);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA8);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA9);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA10);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA11);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA12);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA13);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA14);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA15);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA16);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA17);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA18);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA19);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA20);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA21);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA22);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA23);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA24);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA25);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA26);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA27);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA28);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA29);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA30);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA31);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA32);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA33);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA34);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA35);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA36);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA37);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA38);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA39);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA40);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA41);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA42);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA43);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA44);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA45);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA46);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA47);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA48);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA49);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA50);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA51);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA52);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA53);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA54);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA55);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA56);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA57);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA58);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA59);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA60);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA61);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA62);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA63);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA64);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA65);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA66);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA67);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA68);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA69);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA70);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA71);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA72);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA73);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA74);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA75);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA76);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA77);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA78);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA79);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA80);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA81);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA82);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA83);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA84);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA85);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA86);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA87);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA88);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA89);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA90);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA91);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA92);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA93);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA94);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA95);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA96);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA97);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA98);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA99);
        gabaritoEscalaDePersonalidadeComrey.adicionar(respostaA100);
        //Aqui começa os calculos das escalas do comrey para validação do teste

        System.out.println("T+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaTMais());
        System.out.println("O-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaOMenos());
        System.out.println("C+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaCMais());
        System.out.println("A-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaAMenos());
        System.out.println("");
        System.out.println("S-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaSMenos());
        System.out.println("E+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaEMais());
        System.out.println("M-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaMMenos());
        System.out.println("P+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaPMais());
        System.out.println();
        System.out.println("T-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaTMenos());
        System.out.println("O+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaOMais());
        System.out.println("C-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaCMenos());
        System.out.println("A+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaAMais());
        System.out.println("");
        System.out.println("S+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaSMais());
        System.out.println("E-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaEMenos());
        System.out.println("M+_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaMMais());
        System.out.println("P-_= "+gabaritoEscalaDePersonalidadeComrey.calcularEscalaPMenos());

    }
}
